# Generated by Django 4.0.6 on 2022-08-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10)),
                ('address', models.TextField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_picture', models.ImageField(default=False, upload_to='')),
                ('marital_status', models.CharField(blank=True, max_length=10)),
                ('signature', models.ImageField(upload_to='images/')),
                ('employment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
