# Generated by Django 4.0.6 on 2022-08-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Account_type', models.CharField(max_length=15)),
                ('balance', models.ImageField(upload_to='')),
                ('account_type', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_origin', models.CharField(max_length=25)),
                ('currency_rate', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.customer')),
                ('balance', models.IntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField()),
                ('datecrated', models.DateField()),
                ('type', models.CharField(max_length=15)),
                ('bank_account_name', models.CharField(max_length=15)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_charge', models.CharField(max_length=3)),
                ('transaction_cost', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('account_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_account_origin', to='wallet.account')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destinations', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('transaction_cost', models.ImageField(upload_to='')),
                ('active', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_account', to='wallet.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_currency', to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.PositiveIntegerField()),
                ('date_time_received', models.DateTimeField()),
                ('transactin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction')),
                ('walleT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='media/')),
                ('date', models.DateField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateField()),
                ('time', models.TimeField()),
                ('Message', models.CharField(max_length=15)),
                ('isactive', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.ImageField(upload_to='')),
                ('Loan_type', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('Due_date', models.DateField()),
                ('loan_term', models.CharField(max_length=15)),
                ('Interest_rate', models.IntegerField()),
                ('Payment_date', models.DateField()),
                ('duration', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
                ('Loan_status', models.CharField(max_length=25)),
                ('guaranter', models.CharField(max_length=15)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_name', models.CharField(max_length=15)),
                ('Date_issued', models.DateTimeField()),
                ('Card_number', models.CharField(max_length=15)),
                ('Signature', models.CharField(max_length=15)),
                ('Expiry_date', models.DateField()),
                ('Card_status', models.CharField(max_length=15)),
                ('Security_code', models.PositiveSmallIntegerField()),
                ('issuer', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
    ]
