# Generated by Django 4.0.6 on 2022-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_wallet_transaction_third_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account_type',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country_origin',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
