# Generated by Django 4.0.6 on 2022-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Message',
            field=models.CharField(max_length=40),
        ),
    ]
