# Generated by Django 4.0.6 on 2022-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Card_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guaranter',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='third_party',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
    ]
