# Generated by Django 4.0.6 on 2022-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_card_card_name_alter_card_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Interest',
            field=models.IntegerField(),
        ),
    ]
