# Generated by Django 4.0.6 on 2022-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_third_party_transaction_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Loan_type',
            new_name='loan_type',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='transactin',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='walleT',
            new_name='wallet',
        ),
    ]
