# Generated by Django 4.0.6 on 2022-08-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_card_name_card_card_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='datecreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='third_party',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='third_party',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='type',
            new_name='wallet_type',
        ),
    ]
